spring:
  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: "jdbc:mysql://localhost:3306/test"
    username: dev
    password: dev
